export const GAME_TEST = 'GAME_TEST';
export const GAME_ARKANOID_PART_ONE = 'GAME_ARKANOID_PART_ONE';
export const GAME_ARKANOID_PART_TWO = 'GAME_ARKANOID_PART_TWO';
export const GAME_ARKANOID_PART_THREE = 'GAME_ARKANOID_PART_THREE';
